### ISSUE TITLE
Properly including (and updating) the Visual Glossary

### ISSUE THREAD

**Issue by MikelSalazar** [opengeospatial/GeoPoseGuides#46]
I am working on the new and improved Visual Glossary and I wanted to make sure that there are not problems with the adoc format (linking the different concepts) and there are no logical inconsistencies.

Steve, can we create some sort of template so that I can include the different concepts (separated in sections) and the anchor/ink systems works properly across different files?

**Comment by 3DXScape** [comment]
I made these minor changes to Basic_Concepts.adoc :

1. copied Basic_Concepts.adoc to GeoPose repo (I have no write access to this repo so issue comments is my only way to communicate)
2. added table end marker |=== and some blank lines
3. added explicit sizes for columns and images to make AsciiDoctor happy when making PDF and HTML - you will want to tune these parameters
4. added anchors in the form [[_def_bc_somename_]] to first column of each row of the table
5. built HTML and PDF for testing

Linking from an external document seems to work. I don't have write access to this repo so I put results in the main Geopose repo [here](https://github.com/opengeospatial/GeoPose/tree/main/LinkToGuideTable). For testing I hosted the PDF file on geopose.io and here is a test link to the GeoPose definition in your glossary: [geopose](https://geopose.io/test/keyconcepts.pdf#def_bc_geopose) 

Just change def_bc_geopose to match other anchors. In Chrome, I had to do a refresh on each link test.

I was mildly surprised that it works as it should.

**Comment by cperey** [comment]
@3DXScape I’ve invited you to the repository

**Comment by 3DXScape** [comment]
Thanks. I copied the suggestions to a temporary branch "link_to_rows". Mikel you can merge or delete this branch as you choose.

**Comment by MikelSalazar** [comment]
Hello Steve,

   Now that I have finally found the time to continue working on the new
version of the Visual Glossary, I have copied your template into my
documents and it works perfectly. However, since we need to apply the same
anchor formatting to the other documents, I would like to remove the "_bc"
part from the anchors (that I believe stands for "Basic Concepts"), to
simplify things and just leave as "[[*def_**concept_name*]]. Would it work
for you?

   Apart from that, after reviewing aerospace-related documentation, I
believe we have to modify some of the basic concepts to account for
different types of reference frames (inertial and non-inertial) and
acknowledge the existence of vehicles that can have reference frames
independent of that of the Earth.

   Also, I believe it will be really necessary clarify the differences
between the concepts of *Location* (a region of space with its own
reference Frame), *Position* (a point vector in an inertial Frame) and
*Translation* (a point vector in a non-inertial Frame... because after
reviewing it in depth I have found out I have been saying it wrong all this
time and I have to amend it as soon as possible.

   Thank you for your help,
Mikel Salazar

**Comment by 3DXScape** [comment]
Hello Mikel,

Good. I have been busy too. 

You are correct: I tried to give the identifiers for the definitions enough structure that it would be easy to avoid duplicate names. Any scheme that you want to use is fine for me. Since the identifiers are local to the documents (even though referenced from an external URI) we do not need to maintain uniqueness between documents.

One of the practical problems with concepts is that across application domains there are more concepts than names for the concepts.  The mathematical “pigeonhole principle” https://en.wikipedia.org/wiki/Pigeonhole_principle guarantees confusion :-) The more domain experts, the more overloading of mental abstractions and increasing confusion. This just an observation, not a conclusion or solution or advice. We should discuss in the meeting.

…steve
