### ISSUE TITLE
Visual Glossary: revise section title from “Animation” to “Temporal” 

### ISSUE THREAD

**Issue by cperey** [opengeospatial/GeoPoseGuides#49]
Durng the Sept 3 meeting it was agreed that the section heading "Animation" would be renamed to "Temporal"

**Comment by MikelSalazar** [comment]
Mmmm... now that I have changed it. I realize that the term "Temporal" can lead to confusion (because it can be understood that those concepts are going to be removed afterwards). I am going to change it to "Time-Related Concepts" to avoid misunderstandings. Nevertheless, if you find another, more suitable name, please let me know.

**Comment by cperey** [comment]
Done
